version: 2.1

jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: exit 1
      - run: 
          name: Do when failure occurs
          command: echo "Error!"
          when: on_fail

workflows:
  say-hello-workflow:
    jobs:
      - save_hello_world_output

